import socket

HEADER = 64
PORT = 5050
SERVER  = socket.gethostbyname(socket.gethostname())
ADDR = (SERVER,PORT)
FORMAT = "UTF-8"
DISCONNECT_MESSAGE = "!DISCONNECT!"
REGISTER_MESSAGE = "!REGISTER!"
FOUND_USER_MESSAGE = "!FOUND_USER!"
GET_USER_MESSAGE = "!GET_USER!"
USER_NOT_FOUND = "!USER_NOT_FOUND!"
UPDATE_USER = "!UPDATE_USER_!"